In [1]:
#A quick introduction to NumPy

from numpy import array
mm=array((1,1,1))
pp=array((1,2,3))
pp+mm

array([2, 3, 4])

In [2]:
#Here are some more operations that would require a loop in regular Python: Multiply every number by a constant 2

pp*2

array([2, 4, 6])

In [3]:
#Square every number:

pp**2

array([1, 4, 9])

In [4]:
#You can now access the elements in the array like it was a list:
pp[1]

2

In [5]:
#You can also have multidimensional arrays:
jj = array([[1, 2, 3], [1, 1, 1]])

In [8]:
#These can also be accessed like lists:
jj[0]

array([1, 2, 3])

In [9]:
jj[0][1]

2

In [10]:
#You can also access the elements like a matrix:
jj[0,1]

2

In [11]:
#When you multiply two arrays together, you multiply the elements in the first array by the elements in the second array:
a1=array([1, 2,3])
a2=array([0.3, 0.2, 0.3])
a1*a2

array([0.3, 0.4, 0.9])

In [12]:
#Now let’s talk about matrices: Similar to arrays, you need to import matrix or mat from NumPy:
from numpy import mat, matrix

In [14]:
#The NumPy keyword mat is a shortcut for matrix.

ss = mat([1, 2, 3])
ss

matrix([[1, 2, 3]])

In [15]:
mm = matrix([1, 2, 3])
mm

matrix([[1, 2, 3]])

In [16]:
#You can access the individual elements of a matrix like this:
mm[0,1]

2

In [17]:
#You can convert Python lists into NumPy matrices:
pyList = [5, 11, 1605]
mat(pyList)

matrix([[   5,   11, 1605]])

In [18]:
#Now let’s try to multiply two matrices together:
mm*ss

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

That causes an error and won’t be done. The matrix datatype enforces the mathematics of matrix operations. You can’t multiply a 1x3 matrix by a 1x3 matrix; the inner numbers must match. One of the matrices will need to be transposed so you can multiply a 3x1 and a 1x3 matrix or a 1x3 and a 3x1 matrix. The NumPy matrix data type has a transpose method, so you can do this multiplication quite easily:

In [19]:
mm*ss.T
#We took the transpose of ss with the .T method.

matrix([[14]])

Knowing the dimensions is helpful when debugging alignment errors. If you want to know the dimensions of an array or matrix, you can use the shape function in NumPy:

In [20]:
from numpy import shape
shape(mm)

(1L, 3L)

What if you wanted to multiply every element in matrix **mm** by every element in **ss**? This is known as element-wise multiplication and can be done with the NumPy multiply function:

In [21]:
from numpy import multiply
multiply(mm,ss)

matrix([[1, 4, 9]])

The matrix and array data types have a large number of other useful methods available such as sorting:

In [22]:
mm.sort()
mm 

matrix([[1, 2, 3]])

Be careful; this method does sort in place, so if you want to keep the original order of your data, you must make a copy first. You can also use the argsort() method to give you the indices of the matrix if a sort were to happen:

In [25]:
dd=mat([4,5,1])
dd.argsort()

matrix([[2, 0, 1]], dtype=int64)

You can also calculate the mean of the numbers in a matrix:

In [26]:
dd.mean()

3.3333333333333335

Let’s look at multidimensional arrays for a second:

In [27]:
jj = mat([[1, 2, 3,], [8, 8, 8]])
shape(jj)

(2L, 3L)

This is a matrix of shape 2x3; to get all the elements in one row, you can use the colon (:) operator with the row number. For example, to get all the elements in row 1, you’d enter

In [28]:
jj[1,:]

matrix([[8, 8, 8]])

You can also specify a range of elements. To get all the elements in row 1, columns 0–1, you’d use the following statement:

In [29]:
jj[1,0:2]

matrix([[8, 8]])